set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN K17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {adc[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc[0]}]
set_property PACKAGE_PIN T14 [get_ports {adc[0]}]
set_property PACKAGE_PIN T15 [get_ports {adc[1]}]
set_property PACKAGE_PIN P14 [get_ports {adc[2]}]
set_property PACKAGE_PIN R14 [get_ports {adc[3]}]
set_property PACKAGE_PIN U14 [get_ports {adc[4]}]
set_property PACKAGE_PIN U15 [get_ports {adc[5]}]
set_property PACKAGE_PIN V17 [get_ports {adc[6]}]
set_property PACKAGE_PIN V18 [get_ports {adc[7]}]
set_property PACKAGE_PIN V12 [get_ports {adc[8]}]
set_property PACKAGE_PIN W16 [get_ports {adc[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN Y16 [get_ports reset]
set_property PACKAGE_PIN V15 [get_ports data_out]
set_property IOSTANDARD LVCMOS33 [get_ports data_out]



connect_debug_port u_ila_0/probe0 [get_nets [list {d_out[0]} {d_out[1]} {d_out[2]} {d_out[3]} {d_out[4]} {d_out[5]} {d_out[6]} {d_out[7]} {d_out[8]} {d_out[9]} {d_out[10]} {d_out[11]} {d_out[12]} {d_out[13]} {d_out[14]} {d_out[15]} {d_out[16]} {d_out[17]} {d_out[18]} {d_out[19]} {d_out[20]} {d_out[21]} {d_out[22]} {d_out[23]}]]

